apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: expense
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      project: expense
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "{{ .Chart.Name }}-headless"
  replicas: {{ .Values.statefulset.replicas }} # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        project: expense
        tier: db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Chart.Name }}
        image: joindevops/{{ .Chart.Name }}:{{ .Values.statefulset.version }}
        volumeMounts:
        - name: {{ .Chart.Name }}
          mountPath: /var/lib/{{ .Chart.Name }}
  # Instead of creating a PVC resource, you can directly provide in statefulset
  volumeClaimTemplates:
  - metadata:
      name: {{ .Chart.Name }}
      namespace: expense
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: {{ .Values.statefulset.storage }}